// <auto-generated />
using System;
using ApiCatalog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiCatalog.Migrations
{
    [DbContext(typeof(ApiCatalogContext))]
    partial class ApiCatalogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiCatalog.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            ImageUrl = "comidas.jpg",
                            Name = "Comidas"
                        },
                        new
                        {
                            CategoryId = 2,
                            ImageUrl = "bebidas.jpg",
                            Name = "Bebidas"
                        },
                        new
                        {
                            CategoryId = 3,
                            ImageUrl = "sobremesas.jpg",
                            Name = "Sobremesas"
                        });
                });

            modelBuilder.Entity("ApiCatalog.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Inventory")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Date = new DateTime(2022, 9, 21, 19, 1, 23, 511, DateTimeKind.Local).AddTicks(3618),
                            Description = "Lasanha congelada",
                            ImageUrl = "lasanha.jpg",
                            Inventory = 25,
                            Name = "Lasanha",
                            Price = 15.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            Date = new DateTime(2022, 9, 21, 19, 1, 23, 511, DateTimeKind.Local).AddTicks(3629),
                            Description = "Refrigerante Guaraná 2L",
                            ImageUrl = "guarana.jpg",
                            Inventory = 54,
                            Name = "Guaraná",
                            Price = 7.5
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3,
                            Date = new DateTime(2022, 9, 21, 19, 1, 23, 511, DateTimeKind.Local).AddTicks(3630),
                            Description = "Sobremesa deliciosa. Acompanha sorvete",
                            ImageUrl = "petit-gateau.jpg",
                            Inventory = 17,
                            Name = "Petit Gateau",
                            Price = 20.0
                        });
                });

            modelBuilder.Entity("ApiCatalog.Models.Product", b =>
                {
                    b.HasOne("ApiCatalog.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ApiCatalog.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
